### ISSUE TITLE
bootstrap4 collapse 手风琴无动画效果

### ISSUE THREAD

**Issue by mimimiaomiao1** [yoyomooc/asp.net-core--for-beginner#8]
### Describe the bug 该问题是怎么引起的？
bootstrap4 collapse 手风琴无动画效果

大佬。我很喜欢你的项目。。样式UI非常棒。符合现代设计，但是折叠是无动画效果的。是否跟框架集成中某个东西发生了冲突？ 又或者能否分享一下。。这个框架是用了什么UI 主题？

**Comment by ltm0203** [comment]
大多数的项目都是基于bootstrap的，而 要实现手风琴效果都是靠cSS完成的，你可以学习bootstrap4 的基础来了解。

**Comment by mimimiaomiao1** [comment]
> 大多数的项目都是基于bootstrap的，而 要实现手风琴效果都是靠cSS完成的，你可以学习bootstrap4 的基础来了解。

不是吧，你的项目52abp UI是用的第三方的，你的项目是用的stream，第三方基于bootstrap4的，更新一年前的了。但是手风琴class的写法不一样，bootstrap4的复制过来没法用，了解bootstrap4的用法在你这也没法用啊。不过没关系了。已经找到官方连接了。打扰了。谢谢。已经换官方abp的了。。adminlte+stream。
